name: Dotnet.Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Setup .NET core 2.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '2.0'
      
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Dotnet Release Build
        run: dotnet build -c Release --no-restore

      - name: Upload Release Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: /home/runner/work/dotnet-hello-world/dotnet-hello-world/hello-world-api/bin/Release/netcoreapp2.0/

      - name: Dotnet Debug Build
        run: dotnet build -c Debug --no-restore

      - name: Upload Debug Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: /home/runner/work/dotnet-hello-world/dotnet-hello-world/hello-world-api/bin/Debug/netcoreapp2.0/
          